### ISSUE TITLE
how to get access to the highlighted from available list item?

### ISSUE THREAD

**Issue by VisheshSingh** [jakezatecky/react-dual-listbox#111]
Is there a way to get access to the list item from the _available_ box once it is clicked? 
I would like to override the default highlighted blue color when you select an item. 
When I inspect via React dev tools I am noticing the state (as shown in the screenshot below) contains the highlighted item but I am not sure how to access it.

<img width="898" alt="react dual listbox" src="https://user-images.githubusercontent.com/14873102/81766631-1ec11200-949c-11ea-8ac3-ead3dd1340fb.png">

**Comment by jakezatecky** [comment]
You can pass in the `availableRef` property to the main component:

``` jsx
class Widget {
  constructor(super) {
    this.available = React.createRef();
  }

  ...

  render() {
    ...

    return <DualListbox availableRef={this.available} ... />;
  }
}
```

Then you can call `this.available.value`.

**Comment by VisheshSingh** [comment]
I tried using _availableRef_ but I am hitting a TypeError: n is not a function
Wondering if there is something I am missing? 🙄
Here is the codesandbox url that I am using to test - 
https://codesandbox.io/s/react-dual-listbox-example-jh7me?file=/src/components/Widget.js

**Comment by jakezatecky** [comment]
The code was written pre-React 16.3, where all `ref`s were functions. I forgot about this. You will have to use the following code instead:

``` jsx
class Widget extends React.Component {
  state = {};

  onChange = (selected) => {
      this.setState({ selected });
  };

  componentDidMount() {
      console.log(this.available);
  }

  render() {
      const { selected } = this.state;

      return (
          <DualListBox
              options={options}
              ref={this.listbox}
              availableRef={(c) => { this.available = c; }}
              selected={selected}
              onChange={this.onChange}
          />
      );
  }
}
```

However, upon re-reading your use case, I am not sure having direct access to the DOM node will solve much. What you are looking at in the React dev tools is the underlying `ListBox` component; this is not surfaced to the caller. You could, however, recreate its state by looking at `this.available.selected` (although, not in `render`, as `this.available` would not be defined until after the initial render).

Even if you had access to `ListBox`, I am skeptical that you can do much to override the default blue background. Select boxes have notoriously few customization options, and that is what this component uses underneath. I also have little interest at this time replacing the native `<select>` with something more custom, due to the additional effort involved.

**Comment by VisheshSingh** [comment]
Thanks @jakezatecky 
I forked the project to access the underlying Listbox and then realized there is some extra work I need to do but yes, your suggestion makes sense. 🙌

**Comment by akhilsood** [comment]
Do we have any callback for the selected option, I want to perform some task when some option is selected in "Selected List"

**Comment by jakezatecky** [comment]
Sorry for the delayed response. No, there is not a callback available, but you can attach one yourself. See [this example](https://github.com/jakezatecky/react-dual-listbox/issues/131#issuecomment-791506231).
