### ISSUE TITLE
React dual listbox not working in IE 11

### ISSUE THREAD

**Issue by vishalZscaler** [jakezatecky/react-dual-listbox#158]
**Describe the bug**
I am trying to use simple react dual list box from the package.
but i am getting crypto is undefined error inside IE browser 

**Reproduction steps**
**https://codesandbox.io/s/n37xxln954**
I am using exact snippet added in above link.

**Expected behavior**
React dual list box should be loaded inside IE 11.

**Comment by jakezatecky** [comment]
That crypto error occurs due to the UUID library this component is using to generate unique IDs for the underlying HTML nodes.

I am reluctant to support IE11 due to its legacy status. IE11 implements crypto with the `ms` prefix, but I do not know wheter it supports all of the modern functions the UUID dependency uses.

You can try setting the `id` property on the tree, which should avoid the UUID library, and see if that avoids the `window.crypto` undefined error. Alternatively, if that does not work, a polyfill for IE11 to support crypto would be necessary.

**Comment by vishalZscaler** [comment]
@jakezatecky Adding id using uuid library IE11 worked for me . Thank you for your help :) ...
