### ISSUE TITLE
Integrate in a form using react-hook-form

### ISSUE THREAD

**Issue by asifka** [jakezatecky/react-dual-listbox#214]
how can I integrate with react-hook-form?
I need to validate the dual list and submit data using the hook form

Thanks

**Comment by jakezatecky** [comment]
I have never used that library, but from my understanding (which could be wrong) you can just `register` this component.

There is an underling `<input>` within this component the pairs with the `name` property. This component also uses the standard `value`, `required`, and `disabled` properties that a normal HTML form element would use, so I assume it should work with `react-hook-form` either out of the box or with some minor tweaking.

If someone encounters an issue and can suggest a modification to make this component integrate with `react-hook-form`, then I can I accommodate such changes. Otherwise, I will assume this is a userland implementation.
