### ISSUE TITLE
Subgroup?

### ISSUE THREAD

**Issue by Infemo** [jakezatecky/react-dual-listbox#25]
Is there any solution to add subgroups to group?

**Comment by jakezatecky** [comment]
This library uses the native HTML `optgroups`. [According to the HTML5 spec](http://w3c.github.io/html-reference/optgroup.html#optgroup), the only valid child of an `optgroup` is an `option`. Unfortunately, since HTML5 does not support nested `optgroups` at this time, I am reluctant to implement it in this library.

It certainly would be possible to use something else beyond the traditional `<select>`, `<optgroup>`, and `<option>`, but it would result in the library being a little more complicated. Further, it would be less semantic, and one of the things I am very big about is trying to have as much semantic meaning as possible.
