### ISSUE TITLE
Make Header Labels modifiable

### ISSUE THREAD

**Issue by Ogskun** [jakezatecky/react-dual-listbox#295]
Is it possible to update the Header title of both ListBox? and make it possible to add custom class(CSS/tailwind) for the label styling.

**Comment by jakezatecky** [comment]
Yes, you can update the header labels. You need to pass in a `lang` property and set the `availableHeader` and `selectedHeader` attributes. See the default [`lang`](https://github.com/jakezatecky/react-dual-listbox/blob/master/src/js/lang/default.js) for reference.

For styling, you would need to override the `.rdl-control-label` class with CSS. The component does not allow you to specify a custom class for the headers.

If you are using something like Sass and Tailwind, you could define a `.rdl-control-label` rule and use `@extend` from Tailwind's classes. Otherwise, you will need to just define the CSS rules yourself.

**Comment by Ogskun** [comment]
`
<DualListBox
    showHeaderLabels={true}
    lang={{
          selectedHeader: 'Foo', 
          availableHeader: 'Bar', 
    }}
    options={OPTIONS}
    selected={selected}
    onChange={(value) => setSelected(value)}
    icons={{
          moveAllToAvailable: <ChevronsLeft />,
          moveToAvailable: <ChevronLeft />,
          moveToSelected: <ChevronRight />,
          moveAllToSelected: <ChevronsRight />,
    }}
/>
`

Thank u sir.
