### ISSUE TITLE
Required props need to be added. How to set required list box so user need to select at-least one option

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [jakezatecky/react-dual-listbox#52]
I want to set the list-box to be selected as required. If user does not move any of the item in selected list then form should not be submitted.It should be like we use in select box to show required field.

**Comment by jakezatecky** [comment]
This should be easy to add.

**Comment by jakezatecky** [comment]
On second glance, this is not so trivial to add due to "required" in the case of this component means that values must exist in the "selected" list box.  The browser would think required means having a selection in the rightmost box, but that is not what we necessarily want.

While I could relatively easily add in the logic to make the component show a required message when the form goes from valid to invalidate state, it is much harder to capture (and indeed, prevent) the situation of where a form is submitted and no selections have been made. Under the hood, this component uses a hidden input element and according to the HTML spec hidden inputs cannot be validated (or have the "required" property). There are ways to work around this, but they may require a little more effort.

**Comment by AbhaysinghBhosale** [comment]
@jakezatecky  Yes we don't want to add required to the right box. We want to check that user have moved at-least one option from left to right. In my case ask have radio with 1) All option 2) Selected option , now in case of radio selected option user should be forces to select a option OR select first radio 'All options'

**Comment by usahai** [comment]
Hey! First off, great component. Its being used widely across multiple apps in my workplace.

I had a question regarding the required nature of the problem. I currently have a tie-in with react-final-form. The component is a part of a form, which has other fields. Normally, I would use a <Field> element to trigger the validations. However, I have put the duallistbox as a standalone item in the page. If I click the submit button without moving any items, it will not react. However, if I move at least 1 item over to the selected side, the form is able to submit. My assumption is that some element in tying in with react-final-form, and is somehow tripping up the form submission. Since react-final-form is subscription based, I am having difficulty in tracking which value is causing the submission to trip.

My use case is not that I want to allow the form to submit without any labels being moved, but rather I want to be able to catch the error, so that I can display an error message. I do have a manual workaround, but it is long-winded. A solution native to the component, i.e. if the attribute causing the form to prevent submission were exposed, would greatly reduce the code base. I'm using this component in multiple places, and it would be a great help if I didn't have to manage the state of each submission manually.

I can build a sandbox if you'd like, but I'd need some time.

Once again, thanks for the great component!
