### ISSUE TITLE
Support search and filter

### ISSUE THREAD

**Issue by tanyewei** [jakezatecky/react-dual-listbox#6]

**Comment by jakezatecky** [comment]
Are you referring to a search bar or something on top of the leftmost component? It is certainly possible to filter that list. Not too much effort needed either.

**Comment by jakezatecky** [comment]
I have not put any effort into this. I accidentally touched the labels earlier because I thought I was on a different issue at that point in time.

I have recently squashed all of the other issues for this project, and intend to eventually add this feature, but it is a lower priority item for me right now. I definitely can see the benefit to having searching functionality, but some of my other projects have bugs that I would like to address before adding this newer feature.

That being said, you are welcome to send a PR for this.
