### ISSUE TITLE
Is it possible to add an icon before selected option? Or highlight the option with different colour?

### ISSUE THREAD

**Issue by Lilian1331** [jakezatecky/react-dual-listbox#66]
Is it possible to add an image icon before the selected options? Like this:
![image](https://user-images.githubusercontent.com/23545532/52915493-ab1f6c00-330f-11e9-9c38-c4cc5b6706a7.png)
Or highlight the options with different colours?
Thanks for any help.

**Comment by jakezatecky** [comment]
Extremely late reply (even by my standards), but no this is not possible. The main reason is because this element uses a the native HTML `<select>` and `<option>` tags underneath for simplicity and the `<option>` tag does not really allow complex children. This is related to #38.

It is possible that the component could be retooled to use a more complex combination of tags that mimic the native `<select>` appearance and thus allow for icons to appear before the text, but that is something I am not actively pursuing (though I would accept a PR that includes such changes).

I am going to close this but leave #38 open for the possibility that more customization on the options will be allowed in the future.
