### ISSUE TITLE
Clicking on the icon on the button breaks the component

### ISSUE THREAD

**Issue by hoegertn** [jakezatecky/react-dual-listbox#7]
The onClick method on DualListBox cannot read the move properties if you click on the icon as it then is the target of the event. 

The following snippet would solve this imho:

```
if (target.tagName === 'I') {
  target = target.parentElement;
}
```

**Comment by jakezatecky** [comment]
I will look into this soon. Thanks!

**Comment by 96peerik** [comment]
I think replacing event.target with event.currentTarget will solve this.

https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

**Comment by jakezatecky** [comment]
@96peerik was right. `event.currentTarget` fixes it. Annoyingly, Firefox incorrectly sets `event.target` to the `<button>` DOM element rather than the icon, so when I tested on Firefox I did **not** notice this issue. Affected Chrome and presumably any browser that follows the spec correctly. Ironic that the MDN article correctly defines the behavior of `target` vs. `currentTarget` but Firefox does not follow it properly.
